# This is a basic workflow to help you get started with Actions

name: NODE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add_icons:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run Node
        run: node release/JS/GetFilesToJson.js
      - name: Commit
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
    with:
    # The name of the user that will be displayed as the author of the commit.
    # Default: depends on the default_author input
    author_name: Github Workflow

    # The email of the user that will be displayed as the author of the commit.
    # Default: depends on the default_author input
    author_email: github@trtle.xyz